# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 542)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 5)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 4, 1, 1)
        self.pushButton_browse = QtWidgets.QPushButton(self.tab)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.gridLayout_3.addWidget(self.pushButton_browse, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 3, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_5.addWidget(self.lineEdit_37, 3, 9, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_22.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_5.addWidget(self.pushButton_22, 7, 3, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_5.addWidget(self.lineEdit_25, 6, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_21.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_5.addWidget(self.pushButton_21, 6, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 6, 0, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_5.addWidget(self.lineEdit_31, 7, 5, 1, 2)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_5.addWidget(self.lineEdit_36, 2, 9, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 6, 4, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 7, 4, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 3, 7, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 3, 4, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_5.addWidget(self.lineEdit_38, 6, 9, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_5.addWidget(self.lineEdit_24, 3, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 2, 7, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 6, 7, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_5.addWidget(self.lineEdit_29, 3, 5, 1, 2)
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_19.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_5.addWidget(self.pushButton_19, 3, 3, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_5.addWidget(self.checkBox_5, 17, 5, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_5.addWidget(self.checkBox_6, 17, 6, 1, 2)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_5.addWidget(self.checkBox_7, 17, 8, 1, 2)
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 3, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_5.addWidget(self.checkBox_4, 17, 4, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 17, 0, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_5.addWidget(self.lineEdit_30, 6, 5, 1, 2)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_16.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_5.addWidget(self.pushButton_16, 0, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_5.addWidget(self.lineEdit_22, 0, 1, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_5.addWidget(self.lineEdit_35, 1, 9, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 2, 4, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_5.addWidget(self.comboBox_7, 1, 5, 1, 2)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_5.addWidget(self.lineEdit_23, 2, 1, 1, 3)
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 1, 4, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 1, 7, 1, 2)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_5.addWidget(self.comboBox_6, 0, 5, 1, 2)
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 0, 7, 1, 2)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_5.addWidget(self.lineEdit_34, 0, 9, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_5.addWidget(self.comboBox_5, 1, 1, 1, 3)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 2, 0, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_5.addWidget(self.lineEdit_28, 2, 5, 1, 2)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_5.addWidget(self.lineEdit_26, 7, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 7, 0, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_5.addWidget(self.lineEdit_27, 8, 1, 1, 3)
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 8, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 8, 4, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_5.addWidget(self.lineEdit_32, 8, 5, 1, 2)
        self.label_46 = QtWidgets.QLabel(self.groupBox_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 7, 7, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_5.addWidget(self.lineEdit_39, 7, 9, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_2)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 8, 7, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_5.addWidget(self.lineEdit_40, 8, 9, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_5.addWidget(self.lineEdit_33, 17, 1, 1, 3)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 2, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_6.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 2, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit.setStyleSheet("background-color: rgb(60, 60, 90);\n"
"color: rgb(170, 255, 255);\n"
"font: 11pt \"Microsoft JhengHei\";")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(645, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 2, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_9.addWidget(self.pushButton_13, 2, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_9.addWidget(self.pushButton_12, 2, 2, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_8.setSpacing(2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit_2.setStyleSheet("background-color: rgb(60, 60, 90);\n"
"color: rgb(170, 255, 255);\n"
"font: 11pt \"Microsoft JhengHei\";")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_8.addWidget(self.plainTextEdit_2, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 1, 0, 1, 3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 2, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 3, 3, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_7.addWidget(self.lineEdit_13, 1, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 3, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_7.addWidget(self.comboBox_2, 2, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 4, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_7.addWidget(self.lineEdit_5, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 5, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_7.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_7.addWidget(self.lineEdit_7, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 3, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_7.addWidget(self.lineEdit_11, 6, 1, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_7.addWidget(self.lineEdit_9, 4, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_7.addWidget(self.lineEdit_8, 3, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_7.addWidget(self.lineEdit_10, 5, 1, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_7.addWidget(self.lineEdit_12, 0, 4, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_7.addWidget(self.comboBox, 3, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 1, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_7.addWidget(self.pushButton_7, 0, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_7.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_9.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_7.addWidget(self.pushButton_9, 6, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_10.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_7.addWidget(self.pushButton_10, 0, 5, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_11.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_7.addWidget(self.pushButton_11, 1, 5, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_7.addWidget(self.checkBox, 4, 3, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_7.addWidget(self.checkBox_2, 5, 3, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_4, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_11.addWidget(self.lineEdit_16, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 6, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_17.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_11.addWidget(self.pushButton_17, 1, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_7)
        self.label_26.setObjectName("label_26")
        self.gridLayout_11.addWidget(self.label_26, 3, 0, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_11.addWidget(self.lineEdit_17, 3, 1, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_20.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_11.addWidget(self.pushButton_20, 3, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setObjectName("label_24")
        self.gridLayout_11.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        self.label_25.setObjectName("label_25")
        self.gridLayout_11.addWidget(self.label_25, 5, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_11.addWidget(self.lineEdit_18, 2, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_18.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_11.addWidget(self.pushButton_18, 2, 2, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_11.addWidget(self.lineEdit_20, 4, 1, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_11.addWidget(self.lineEdit_19, 5, 1, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_11.addWidget(self.lineEdit_21, 6, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 1, 4, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_11.addWidget(self.checkBox_3, 5, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 3, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 4, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_7)
        self.label_27.setObjectName("label_27")
        self.gridLayout_11.addWidget(self.label_27, 2, 4, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_11.addWidget(self.lineEdit_15, 2, 5, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_11.addWidget(self.lineEdit_14, 1, 5, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_11.addWidget(self.comboBox_3, 3, 5, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_11.addWidget(self.comboBox_4, 4, 5, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_7, 0, 0, 1, 3)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_10.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_10.setSpacing(2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.plainTextEdit_3.setStyleSheet("background-color: rgb(60, 60, 90);\n"
"color: rgb(170, 255, 255);\n"
"font: 11pt \"Microsoft JhengHei\";")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout_10.addWidget(self.plainTextEdit_3, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_6, 1, 0, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(645, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem4, 2, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_12.addWidget(self.pushButton_14, 2, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_12.addWidget(self.pushButton_15, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EvisionNet-GUI"))
        self.groupBox.setTitle(_translate("MainWindow", "Log properties"))
        self.label_3.setText(_translate("MainWindow", "Data:"))
        self.label_2.setText(_translate("MainWindow", "Time Stamp:"))
        self.label_4.setText(_translate("MainWindow", "Specifier:"))
        self.pushButton_4.setText(_translate("MainWindow", "DOWN"))
        self.pushButton_browse.setText(_translate("MainWindow", "browse"))
        self.label.setText(_translate("MainWindow", "Log Folder:"))
        self.pushButton_2.setText(_translate("MainWindow", "Open TensorBoard"))
        self.pushButton_3.setText(_translate("MainWindow", "UP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Log Analyzer"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Parameters"))
        self.pushButton_22.setText(_translate("MainWindow", "..."))
        self.pushButton_21.setText(_translate("MainWindow", "..."))
        self.label_30.setText(_translate("MainWindow", "log-summary:"))
        self.label_37.setText(_translate("MainWindow", "batch-size"))
        self.label_38.setText(_translate("MainWindow", "learning-rate"))
        self.label_44.setText(_translate("MainWindow", "mask-loss-weight"))
        self.label_36.setText(_translate("MainWindow", "epoch-size"))
        self.label_43.setText(_translate("MainWindow", "photo-loss-weight"))
        self.label_45.setText(_translate("MainWindow", "smooth-loss-weight"))
        self.pushButton_19.setText(_translate("MainWindow", "..."))
        self.checkBox_5.setText(_translate("MainWindow", "intri_pred"))
        self.checkBox_6.setText(_translate("MainWindow", "evaluate"))
        self.checkBox_7.setText(_translate("MainWindow", "log-output"))
        self.label_29.setText(_translate("MainWindow", "pretrained-exppose:"))
        self.checkBox_4.setText(_translate("MainWindow", "with-gt"))
        self.label_40.setText(_translate("MainWindow", "beta"))
        self.pushButton_16.setText(_translate("MainWindow", "..."))
        self.label_33.setText(_translate("MainWindow", "rotation-mode"))
        self.label_9.setText(_translate("MainWindow", "DataFlow:"))
        self.label_19.setText(_translate("MainWindow", "dataset-format:"))
        self.label_35.setText(_translate("MainWindow", "epochs"))
        self.label_34.setText(_translate("MainWindow", "padding-mode"))
        self.label_42.setText(_translate("MainWindow", "seed"))
        self.label_41.setText(_translate("MainWindow", "weight-decay"))
        self.label_28.setText(_translate("MainWindow", "workers:"))
        self.label_31.setText(_translate("MainWindow", "log-ful"))
        self.label_32.setText(_translate("MainWindow", "sequence-length"))
        self.label_39.setText(_translate("MainWindow", "momentum"))
        self.label_46.setText(_translate("MainWindow", "print-freq"))
        self.label_47.setText(_translate("MainWindow", "training-output-freq"))
        self.pushButton_6.setText(_translate("MainWindow", "Check"))
        self.pushButton_5.setText(_translate("MainWindow", "Run"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Command Line"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Training"))
        self.pushButton_13.setText(_translate("MainWindow", "Check"))
        self.pushButton_12.setText(_translate("MainWindow", "Run"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Command Line"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Params"))
        self.label_16.setText(_translate("MainWindow", "img-exts"))
        self.label_15.setText(_translate("MainWindow", "gt-type:"))
        self.label_13.setText(_translate("MainWindow", "dataset-list:"))
        self.label_10.setText(_translate("MainWindow", "min-depth:"))
        self.label_5.setText(_translate("MainWindow", "pretrained-dispnet:"))
        self.label_6.setText(_translate("MainWindow", "pretrained-posenet"))
        self.label_11.setText(_translate("MainWindow", "max-depth:"))
        self.label_7.setText(_translate("MainWindow", "img-height:"))
        self.label_12.setText(_translate("MainWindow", "dataset-dir:"))
        self.label_8.setText(_translate("MainWindow", "img-width:"))
        self.label_14.setText(_translate("MainWindow", "output-dir:"))
        self.pushButton_7.setText(_translate("MainWindow", "..."))
        self.pushButton_8.setText(_translate("MainWindow", "..."))
        self.pushButton_9.setText(_translate("MainWindow", "..."))
        self.pushButton_10.setText(_translate("MainWindow", "..."))
        self.pushButton_11.setText(_translate("MainWindow", "..."))
        self.checkBox.setText(_translate("MainWindow", "no-resize"))
        self.checkBox_2.setText(_translate("MainWindow", "GPS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Test Disp"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Params"))
        self.label_21.setText(_translate("MainWindow", "pretrained-posenet"))
        self.label_23.setText(_translate("MainWindow", "img-height:"))
        self.label_20.setText(_translate("MainWindow", "min-depth:"))
        self.pushButton_17.setText(_translate("MainWindow", "..."))
        self.label_26.setText(_translate("MainWindow", "output-dir:"))
        self.pushButton_20.setText(_translate("MainWindow", "..."))
        self.label_24.setText(_translate("MainWindow", "dataset-dir:"))
        self.label_25.setText(_translate("MainWindow", "img-width:"))
        self.pushButton_18.setText(_translate("MainWindow", "..."))
        self.label_22.setText(_translate("MainWindow", "max-depth:"))
        self.checkBox_3.setText(_translate("MainWindow", "no-resize"))
        self.label_17.setText(_translate("MainWindow", "img-exts"))
        self.label_18.setText(_translate("MainWindow", "rotation-mode"))
        self.label_27.setText(_translate("MainWindow", "sequences:"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Command Line"))
        self.pushButton_14.setText(_translate("MainWindow", "Check"))
        self.pushButton_15.setText(_translate("MainWindow", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Test Pose"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Examples"))

