# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EvisionNet_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 587)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_TimeStamp = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_TimeStamp.setObjectName("lineEdit_TimeStamp")
        self.gridLayout_2.addWidget(self.lineEdit_TimeStamp, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_Data = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Data.setObjectName("lineEdit_Data")
        self.gridLayout_2.addWidget(self.lineEdit_Data, 1, 1, 1, 1)
        self.label_Specifier = QtWidgets.QLabel(self.groupBox)
        self.label_Specifier.setObjectName("label_Specifier")
        self.gridLayout_2.addWidget(self.label_Specifier, 2, 0, 1, 1)
        self.lineEdit_Specifier = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Specifier.setObjectName("lineEdit_Specifier")
        self.gridLayout_2.addWidget(self.lineEdit_Specifier, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 5)
        self.pushButton_brewse = QtWidgets.QPushButton(self.tab)
        self.pushButton_brewse.setObjectName("pushButton_brewse")
        self.gridLayout_3.addWidget(self.pushButton_brewse, 0, 2, 1, 1)
        self.pushButton_UP = QtWidgets.QPushButton(self.tab)
        self.pushButton_UP.setObjectName("pushButton_UP")
        self.gridLayout_3.addWidget(self.pushButton_UP, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_LogFolder = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_LogFolder.setObjectName("lineEdit_LogFolder")
        self.gridLayout_3.addWidget(self.lineEdit_LogFolder, 0, 1, 1, 1)
        self.pushButton_DOWN = QtWidgets.QPushButton(self.tab)
        self.pushButton_DOWN.setObjectName("pushButton_DOWN")
        self.gridLayout_3.addWidget(self.pushButton_DOWN, 0, 4, 1, 1)
        self.pushButton_OpenTensorBoard = QtWidgets.QPushButton(self.tab)
        self.pushButton_OpenTensorBoard.setObjectName("pushButton_OpenTensorBoard")
        self.gridLayout_3.addWidget(self.pushButton_OpenTensorBoard, 2, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 2, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_6.addWidget(self.pushButton_6, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit.setStyleSheet("background-color: rgb(60, 60, 90);\n"
"color: rgb(170, 255, 255);\n"
"font: 11pt \"Microsoft JhengHei\";")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 1, 0, 1, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableView = QtWidgets.QTableView(self.groupBox_2)
        self.tableView.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(170, 255, 255);\n"
"font: 11pt \"Microsoft JhengHei\";")
        self.tableView.setObjectName("tableView")
        self.gridLayout_5.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EvisionNet-GUI"))
        self.groupBox.setTitle(_translate("MainWindow", "Log properties"))
        self.label_2.setText(_translate("MainWindow", "Time Stamp:"))
        self.label_3.setText(_translate("MainWindow", "Data:"))
        self.label_Specifier.setText(_translate("MainWindow", "Specifier:"))
        self.pushButton_brewse.setText(_translate("MainWindow", "browse"))
        self.pushButton_UP.setText(_translate("MainWindow", "UP"))
        self.label.setText(_translate("MainWindow", "Log Folder:"))
        self.pushButton_DOWN.setText(_translate("MainWindow", "DOWN"))
        self.pushButton_OpenTensorBoard.setText(_translate("MainWindow", "Open TensorBoard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Log Analyzer"))
        self.pushButton_5.setText(_translate("MainWindow", "Run"))
        self.pushButton_6.setText(_translate("MainWindow", "Check"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Command Line"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Parameters"))
        self.tableView.setToolTip(_translate("MainWindow", "<html><head/><body><p>table</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Training"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Testing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Examples"))
